name: Daily 10x Auto Push

on:
  schedule:
    - cron: '45 11 * * *' # Roz 4:45 PM Pakistan time (UTC+5)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Make 10 commits
        run: |
          for i in {1..10}
          do
            echo "Auto update $i at $(date)" >> daily_log.txt
            git add .
            git commit -m "Auto commit $i"
          done

      - name: Push changes
        run: |
          git push
